# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: nginx
#   namespace: {{ .Values.user.namespace }}
# spec:
#   controller: k8s.io/ingress-nginx
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.user.namespace }}
#   name: shop-ingress
#   namespace: shop
  {{- if .Values.ingress.annotations}}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations}}
      {{ $key }}: {{ $value | quote }}
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # cert-manager.io/cluster-issuer: letsencrypt
  {{- end }}
  {{- end }}
spec:
  ingressClassName: nginx
  # name: {{ .Values.ingress.name }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.ingress.path.user }}
            backend:
              service:
                name: {{ .Values.user.name }}
                port:
                  name: {{ .Values.user.portName }}
          - pathType: Prefix
            path: {{ .Values.ingress.path.product }}
            backend:
              service:
                name: {{ .Values.product.name}}
                port:
                  name: {{ .Values.product.portName }}
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: my-tls-secret