// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: worker_rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginTimestampReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *LoginTimestampReq) Reset() {
	*x = LoginTimestampReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginTimestampReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTimestampReq) ProtoMessage() {}

func (x *LoginTimestampReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTimestampReq.ProtoReflect.Descriptor instead.
func (*LoginTimestampReq) Descriptor() ([]byte, []int) {
	return file_worker_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *LoginTimestampReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SendWelcomeEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SendWelcomeEmailReq) Reset() {
	*x = SendWelcomeEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWelcomeEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWelcomeEmailReq) ProtoMessage() {}

func (x *SendWelcomeEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWelcomeEmailReq.ProtoReflect.Descriptor instead.
func (*SendWelcomeEmailReq) Descriptor() ([]byte, []int) {
	return file_worker_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SendWelcomeEmailReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SendWelcomeEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_worker_rpc_proto protoreflect.FileDescriptor

var file_worker_rpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2f, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x57,
	0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_worker_rpc_proto_rawDescOnce sync.Once
	file_worker_rpc_proto_rawDescData = file_worker_rpc_proto_rawDesc
)

func file_worker_rpc_proto_rawDescGZIP() []byte {
	file_worker_rpc_proto_rawDescOnce.Do(func() {
		file_worker_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_worker_rpc_proto_rawDescData)
	})
	return file_worker_rpc_proto_rawDescData
}

var file_worker_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_worker_rpc_proto_goTypes = []interface{}{
	(*LoginTimestampReq)(nil),   // 0: pb.LoginTimestampReq
	(*SendWelcomeEmailReq)(nil), // 1: pb.SendWelcomeEmailReq
}
var file_worker_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worker_rpc_proto_init() }
func file_worker_rpc_proto_init() {
	if File_worker_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_worker_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginTimestampReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWelcomeEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_worker_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_worker_rpc_proto_goTypes,
		DependencyIndexes: file_worker_rpc_proto_depIdxs,
		MessageInfos:      file_worker_rpc_proto_msgTypes,
	}.Build()
	File_worker_rpc_proto = out.File
	file_worker_rpc_proto_rawDesc = nil
	file_worker_rpc_proto_goTypes = nil
	file_worker_rpc_proto_depIdxs = nil
}
